CREATE TABLE IF NOT EXISTS logdata (
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    level VARCHAR NOT NULL,
    service VARCHAR NOT NULL,
    message TEXT NOT NULL
);
