// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logdata.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLogData = `-- name: GetLogData :many
SELECT timestamp, level, service, message FROM logdata
`

type GetLogDataRow struct {
	Timestamp pgtype.Timestamptz
	Level     string
	Service   string
	Message   string
}

func (q *Queries) GetLogData(ctx context.Context) ([]GetLogDataRow, error) {
	rows, err := q.db.Query(ctx, getLogData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLogDataRow{}
	for rows.Next() {
		var i GetLogDataRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.Level,
			&i.Service,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeLogData = `-- name: StoreLogData :exec
INSERT INTO logdata (timestamp, level, service, message) VALUES ($1, $2, $3, $4)
`

type StoreLogDataParams struct {
	Timestamp pgtype.Timestamptz
	Level     string
	Service   string
	Message   string
}

func (q *Queries) StoreLogData(ctx context.Context, arg StoreLogDataParams) error {
	_, err := q.db.Exec(ctx, storeLogData,
		arg.Timestamp,
		arg.Level,
		arg.Service,
		arg.Message,
	)
	return err
}
